name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2

    - name: Start database with Docker Compose
      run: |
        # Create a temporary docker-compose file for testing
        cat > docker-compose.test.yml << EOF
        version: '3'
        services:
          mysql:
            image: mysql:8.0
            environment:
              - MYSQL_ROOT_PASSWORD=\${{ secrets.MYSQL_ROOT_PASSWORD }}
              - MYSQL_DATABASE=\${{ secrets.DB_NAME }}
              - MYSQL_USER=\${{ secrets.DB_USER }}
              - MYSQL_PASSWORD=\${{ secrets.DB_PASSWORD }}
            ports:
              - 3306:3306
            healthcheck:
              test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p\${{ secrets.MYSQL_ROOT_PASSWORD }}"]
              interval: 5s
              timeout: 5s
              retries: 5
        EOF
        docker compose -f docker-compose.test.yml up -d
        
    - name: Wait for database to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        timeout=60
        until docker compose -f docker-compose.test.yml exec -T mysql mysqladmin ping -h localhost -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} --silent || [ $timeout -le 0 ]; do
          sleep 1
          ((timeout--))
        done
        if [ $timeout -le 0 ]; then
          echo "MySQL failed to start in time"
          exit 1
        fi
    
    - name: Initialize database
      run: |
        if [ -f schema.sql ]; then
          docker compose -f docker-compose.test.yml exec -T mysql mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} < schema.sql
        else
          echo "Warning: schema.sql not found"
        fi
    
    - name: Run tests
      run: |
        # Add your test commands here
        python -m pytest tests/ || echo "No tests found"
      
    - name: Clean up Docker resources
      run: docker compose -f docker-compose.test.yml down
      if: always()

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: jakubcwiora/simple-meme-site:latest
        build-args: |
          DB_HOST=db
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
